In [19]:
# hyper parameter tuning 
import warnings
warnings.filterwarnings('ignore')

In [20]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x, y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=2, random_state=1)

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [22]:
#hyperparameter tuning
# GridsearchCV

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
params = {'penalty': ('l1', 'l2', 'elasticnet'), 'C': [1, 2, 10, 20, 30, 40]}

In [25]:
classifier  = LogisticRegression()

In [26]:
classifier

LogisticRegression()

In [27]:
clf  = GridSearchCV(classifier, param_grid=params, cv = 5)

In [28]:
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [29]:
clf.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [30]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [32]:
clf.best_score_

np.float64(0.8087500000000001)

In [34]:
model = LogisticRegression(C= 1, penalty='l2')
model

LogisticRegression(C=1)

In [35]:
model.fit(x_train, y_train)

LogisticRegression(C=1)

In [36]:
y_pred  = model.predict(x_test)

In [37]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [38]:
model.predict_proba(x_test)

array([[0.71651923, 0.28348077],
       [0.1950465 , 0.8049535 ],
       [0.12414182, 0.87585818],
       [0.05044049, 0.94955951],
       [0.8877372 , 0.1122628 ],
       [0.75067873, 0.24932127],
       [0.97980988, 0.02019012],
       [0.39209128, 0.60790872],
       [0.59915467, 0.40084533],
       [0.39298278, 0.60701722],
       [0.20417269, 0.79582731],
       [0.80256674, 0.19743326],
       [0.8642444 , 0.1357556 ],
       [0.92666604, 0.07333396],
       [0.00131606, 0.99868394],
       [0.04168894, 0.95831106],
       [0.56294841, 0.43705159],
       [0.89322189, 0.10677811],
       [0.29273031, 0.70726969],
       [0.00870462, 0.99129538],
       [0.71874782, 0.28125218],
       [0.51089475, 0.48910525],
       [0.76228576, 0.23771424],
       [0.73168731, 0.26831269],
       [0.10152661, 0.89847339],
       [0.04045506, 0.95954494],
       [0.57929547, 0.42070453],
       [0.00526033, 0.99473967],
       [0.03099815, 0.96900185],
       [0.96092766, 0.03907234],
       [0.

In [39]:
# Evaluation matrics 
    
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred)) # confusion matrics 
print(accuracy_score(y_test, y_pred)) # accuracy score for tyhe model
print(classification_report(y_test, y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [40]:
# randomized search cv, it will take randomly some combition 

In [44]:
from sklearn.model_selection import RandomizedSearchCV
randomize_clf = RandomizedSearchCV(classifier, param_distributions=params, cv = 5, n_iter=10)

In [46]:
randomize_clf.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [47]:
randomize_clf.best_score_

np.float64(0.8087500000000001)

In [48]:
randomize_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [49]:
model = LogisticRegression(C = 10, penalty='l2')
model

LogisticRegression(C=10)

In [50]:
model.fit(x_train, y_train)

LogisticRegression(C=10)

In [52]:
y_pred = model.predict(x_test)

In [53]:
# Evaluation matrics 
    
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred)) # confusion matrics 
print(accuracy_score(y_test, y_pred)) # accuracy score for tyhe model
print(classification_report(y_test, y_pred))

[[79 12]
 [29 80]]
0.795
              precision    recall  f1-score   support

           0       0.73      0.87      0.79        91
           1       0.87      0.73      0.80       109

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.79       200
weighted avg       0.81      0.80      0.80       200

