In [28]:
from sklearn.datasets import load_iris

In [29]:
data = load_iris()

In [30]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [31]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [32]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [33]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
import pandas as pd
import numpy as np 

In [35]:
np.unique(data.target)

array([0, 1, 2])

In [36]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['terget'] = data.target

In [37]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),terget
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [38]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),terget
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [39]:
df.sample()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),terget
74,6.4,2.9,4.3,1.3,1


In [40]:
# split manuali x and y
x = df.iloc[:, :-1]
y = df.iloc[:,-1]

In [41]:
x

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [42]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: terget, Length: 150, dtype: int64

In [43]:
# train test split
from sklearn.model_selection import train_test_split

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=1)

In [45]:
x_train.shape, x_test.shape

((105, 4), (45, 4))

In [47]:
# model training 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=300)
classifier

LogisticRegression(max_iter=300)

In [48]:
classifier.fit(x_train, y_train)

LogisticRegression(max_iter=300)

In [51]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1])

In [53]:
classifier.predict_proba(x_test)

array([[9.85025413e-01, 1.49745022e-02, 8.47908370e-08],
       [2.73870283e-01, 7.22403437e-01, 3.72627969e-03],
       [6.87876609e-03, 8.67910310e-01, 1.25210924e-01],
       [9.85580992e-01, 1.44187832e-02, 2.25307987e-07],
       [1.61763886e-06, 1.99352973e-02, 9.80063085e-01],
       [4.82078495e-03, 5.87872896e-01, 4.07306319e-01],
       [1.74155722e-04, 1.29200049e-01, 8.70625795e-01],
       [9.58218340e-01, 4.17781345e-02, 3.52553032e-06],
       [9.68302297e-01, 3.16968616e-02, 8.41644079e-07],
       [1.34383209e-05, 3.10694416e-02, 9.68917120e-01],
       [1.98946892e-02, 8.69217197e-01, 1.10888114e-01],
       [9.67083182e-01, 3.29154198e-02, 1.39858104e-06],
       [7.00815452e-06, 3.82223525e-02, 9.61770639e-01],
       [7.71313177e-03, 7.66892739e-01, 2.25394130e-01],
       [7.47576401e-03, 7.31252914e-01, 2.61271322e-01],
       [9.87344760e-01, 1.26550431e-02, 1.97258907e-07],
       [2.35787059e-02, 9.29632561e-01, 4.67887329e-02],
       [1.15650187e-02, 6.62102

In [54]:
# Evaluation matrics 
    
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred)) # confusion matrics 
print(accuracy_score(y_test, y_pred)) # accuracy score for tyhe model
print(classification_report(y_test, y_pred)) # classification report 

[[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]
0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        18
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

